server:
  port: 8888
  servlet:
    context-path: /iMana

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iMana
    username: temp_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
